---

- name: Main NGINX configurations
  copy:
    src: "files/{{ item.src }}"
    dest: "/etc/nginx/{{ item.dest }}"
  with_items:
    - { src: nginx.conf, dest: nginx.conf }
    - { src: mime.types, dest: mime.types }
    - { src: directive-only, dest: snippets }
    - { src: location, dest: snippets }
    - { src: sites-available/no-default, dest: sites-available/no-default }
    - { src: sites-available/ssl.no-default, dest: sites-available/ssl.no-default }
  notify: restart nginx
  tags: nginx

- name: Remove package default site
  file:
    state: absent
    path: /etc/nginx/sites-available/default
  notify: restart nginx
  tags: nginx

- name: Apply no-default
  file:
    state: link
    src: /etc/nginx/sites-available/{{ item }}
    dest: /etc/nginx/sites-enabled/{{ item }}
  with_items:
    - no-default
    - ssl.no-default
  notify: restart nginx
  tags: nginx